apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "scheduler"
  namespace: "staging"
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - scheduler.staging.revaturelabs.com
    secretName: scheduler-staging-tls
  rules:
  - host: scheduler.staging.revaturelabs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: scheduler
          servicePort: 80
