/**
 * This package contains all of the DAO objects.  Most of the methods are automatically generated by SpringData, so there are only minimal methods
 * @author chris
 *
 */
package com.revature.sms.domain.dao;

